Repository NOW-SOPT-APP8-JUMPIT/Jumpit-Android, pull requests merged in 2024-05, with the labels that each got.

#3 develop: version catalog 적용
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🍭 [DEVELOP], 🍂 [가을], 🏂 [점핏]

#7 develop: color system 구성
  app/src/main/res/values/colors.xml
Labels: 🍭 [DEVELOP], 🍂 [가을], 🏂 [점핏]

#9 develop: font system 구성
  .github/ISSUE_TEMPLATE/default_issue_template.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/now/jumpit/data/NetworkModule.kt
  app/src/main/java/com/sopt/now/jumpit/data/mapper/gitkeep
  app/src/main/java/com/sopt/now/jumpit/data/model/gitkeep
  app/src/main/java/com/sopt/now/jumpit/data/util/gitkeep
  app/src/main/java/com/sopt/now/jumpit/domain/gitkeep
  app/src/main/java/com/sopt/now/jumpit/ui/base/BindingActivity.kt
  app/src/main/java/com/sopt/now/jumpit/ui/base/BindingFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/main/MainActivity.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/values/typography.xml
Labels: 🍭 [DEVELOP], 🐸 [준서], 🏂 [점핏]

#13 develop: SAA 기본 세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/now/jumpit/data/model/BottomNaviItems.kt
  app/src/main/java/com/sopt/now/jumpit/ui/home/HomeFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/jumpit/JumpitActivity.kt
  app/src/main/java/com/sopt/now/jumpit/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumeFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/search/searchFragment.kt
  app/src/main/res/drawable/ic_apply_normal.xml
  app/src/main/res/drawable/ic_employment_normal.xml
  app/src/main/res/drawable/ic_home_normal.xml
  app/src/main/res/drawable/ic_home_selected.xml
  app/src/main/res/drawable/ic_passnote_normal.xml
  app/src/main/res/drawable/ic_resume_normal.xml
  app/src/main/res/drawable/ic_resume_selected.xml
  app/src/main/res/drawable/selector_home_checked.xml
  app/src/main/res/drawable/selector_resume_checked.xml
  app/src/main/res/layout/activity_jumpit.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_resume.xml
  app/src/main/res/menu/menu_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 🍭 [DEVELOP], 🍎 [나경], 🏂 [점핏]

#18 develop: base url 추가
  app/build.gradle.kts
  app/src/main/java/com/sopt/now/jumpit/data/NetworkModule.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/BaseResponse.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/MyResumeResponse.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/gitkeep
  app/src/main/java/com/sopt/now/jumpit/data/remote/service/NoticeService.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/service/ResumeService.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/service/gitkeep
Labels: 🍭 [DEVELOP], 🍂 [가을], 🏂 [점핏]

#16 develop: 검색 페이지 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/now/jumpit/JumpitApp.kt
  app/src/main/java/com/sopt/now/jumpit/data/local/dao/RecentKeywordDao.kt
  app/src/main/java/com/sopt/now/jumpit/data/local/database/LocalDatabase.kt
  app/src/main/java/com/sopt/now/jumpit/data/model/RecentKeyword.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/SearchResult.kt
  app/src/main/java/com/sopt/now/jumpit/data/repository/SearchKeywordRepository.kt
  app/src/main/java/com/sopt/now/jumpit/ui/base/BaseFactory.kt
  app/src/main/java/com/sopt/now/jumpit/ui/jumpit/JumpitActivity.kt
  app/src/main/java/com/sopt/now/jumpit/ui/search/SearchAdapter.kt
  app/src/main/java/com/sopt/now/jumpit/ui/search/SearchFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/search/SearchViewModel.kt
  app/src/main/java/com/sopt/now/jumpit/ui/search/searchFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchCategoryDialog.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchResultAdapter.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchResultFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchResultViewModel.kt
  app/src/main/java/com/sopt/now/jumpit/util/view/ViewExt.kt
  app/src/main/res/anim/modal_slide_in_bottom.xml
  app/src/main/res/anim/modal_slide_out_bottom.xml
  app/src/main/res/drawable-xhdpi/img_search_ad.png
  app/src/main/res/drawable-xxhdpi/img_search_ad.png
  app/src/main/res/drawable/bg_category_bottom_sheet.xml
  app/src/main/res/drawable/bg_gray_radius_20.xml
  app/src/main/res/drawable/bg_gray_radius_31.xml
  app/src/main/res/drawable/ic_search_bookmark_normal.xml
  app/src/main/res/drawable/ic_search_bookmark_selected.xml
  app/src/main/res/drawable/ic_search_category_bottom_sheet_top.xml
  app/src/main/res/drawable/ic_search_navigate_back.xml
  app/src/main/res/drawable/ic_search_recent_delete.xml
  app/src/main/res/drawable/ic_search_search.xml
  app/src/main/res/drawable/ic_search_toggle.xml
  app/src/main/res/drawable/img_search_ad.png
  app/src/main/res/drawable/img_search_dummy.jpg
  app/src/main/res/drawable/selector_search_bookmark.xml
  app/src/main/res/layout/dialog_search_category.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/item_search_recent.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🍭 [DEVELOP], 🐸 [준서], 🏂 [점핏]

#15 develop: 이력서 페이지 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/now/jumpit/data/remote/request/ResumeEnrollRequest.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/request/ResumePrivateRequest.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/MyResumeResponse.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/ResumeResponse.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/service/ResumeService.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/AddBottomSheetDialogFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/EditBottomSheetDialogFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/Resume.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumeAdapter.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumeEnrollState.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumeFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumePrivateState.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumeViewHolder.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumeViewModel.kt
  app/src/main/res/drawable/ic_resume_add.xml
  app/src/main/res/drawable/ic_resume_close.xml
  app/src/main/res/drawable/ic_resume_detail.xml
  app/src/main/res/drawable/ic_resume_dot.xml
  app/src/main/res/drawable/ic_resume_green_dot.xml
  app/src/main/res/drawable/ic_resume_help.xml
  app/src/main/res/drawable/ic_resume_help_selected.xml
  app/src/main/res/drawable/ic_resume_my.xml
  app/src/main/res/drawable/ic_resume_red_dot.xml
  app/src/main/res/drawable/ic_resume_toggleoff.xml
  app/src/main/res/drawable/ic_resume_toggleon.xml
  app/src/main/res/drawable/selector_resume_toggle.xml
  app/src/main/res/drawable/shape_gray_fill_8_rect.xml
  app/src/main/res/drawable/shape_white_dash_12_rect.xml
  app/src/main/res/drawable/shape_white_fill_12_rect.xml
  app/src/main/res/drawable/shape_white_fill_top12_rect.xml
  app/src/main/res/layout/fragment_add_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_edit_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_resume.xml
  app/src/main/res/layout/item_resume.xml
  app/src/main/res/layout/popup_attachment.xml
  app/src/main/res/layout/popup_resume.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🍭 [DEVELOP], 🍂 [가을], 🏂 [점핏]

#21 develop: 홈 페이지 UI 구현
  app/src/main/java/com/sopt/now/jumpit/ui/home/HomeFragment.kt
  app/src/main/res/drawable-xhdpi/img_home_content.png
  app/src/main/res/drawable-xhdpi/img_home_feed.png
  app/src/main/res/drawable-xhdpi/img_home_grow.png
  app/src/main/res/drawable-xhdpi/img_home_hot.png
  app/src/main/res/drawable-xhdpi/img_home_interview.png
  app/src/main/res/drawable-xhdpi/img_home_logo.png
  app/src/main/res/drawable-xhdpi/img_home_logo_gray.png
  app/src/main/res/drawable-xhdpi/img_home_money.png
  app/src/main/res/drawable-xhdpi/img_home_qna.png
  app/src/main/res/drawable-xhdpi/img_home_read.png
  app/src/main/res/drawable-xhdpi/img_logo.png
  app/src/main/res/drawable-xxhdpi/img_home_content.png
  app/src/main/res/drawable-xxhdpi/img_home_feed.png
  app/src/main/res/drawable-xxhdpi/img_home_grow.png
  app/src/main/res/drawable-xxhdpi/img_home_hot.png
  app/src/main/res/drawable-xxhdpi/img_home_interview.png
  app/src/main/res/drawable-xxhdpi/img_home_logo.png
  app/src/main/res/drawable-xxhdpi/img_home_logo_gray.png
  app/src/main/res/drawable-xxhdpi/img_home_money.png
  app/src/main/res/drawable-xxhdpi/img_home_qna.png
  app/src/main/res/drawable-xxhdpi/img_home_read.png
  app/src/main/res/drawable-xxhdpi/img_logo.png
  app/src/main/res/drawable/btn_home_topbar_aos.xml
  app/src/main/res/drawable/btn_passresume.xml
  app/src/main/res/drawable/btn_seeall_circle.xml
  app/src/main/res/drawable/ic_home_aiml.xml
  app/src/main/res/drawable/ic_home_alarm.xml
  app/src/main/res/drawable/ic_home_android.xml
  app/src/main/res/drawable/ic_home_arrow_r_gray.xml
  app/src/main/res/drawable/ic_home_frontend.xml
  app/src/main/res/drawable/ic_home_jaball.xml
  app/src/main/res/drawable/ic_home_my.xml
  app/src/main/res/drawable/ic_home_notice.xml
  app/src/main/res/drawable/ic_home_qa.xml
  app/src/main/res/drawable/ic_home_search.xml
  app/src/main/res/drawable/ic_home_serverback.xml
  app/src/main/res/drawable/ic_home_swsol.xml
  app/src/main/res/drawable/ic_home_webfull.xml
  app/src/main/res/drawable/img_home_content.png
  app/src/main/res/drawable/img_home_feed.png
  app/src/main/res/drawable/img_home_grow.png
  app/src/main/res/drawable/img_home_hot.png
  app/src/main/res/drawable/img_home_interview.png
  app/src/main/res/drawable/img_home_logo.png
  app/src/main/res/drawable/img_home_logo_gray.png
  app/src/main/res/drawable/img_home_money.png
  app/src/main/res/drawable/img_home_qna.png
  app/src/main/res/drawable/img_home_read.png
  app/src/main/res/drawable/img_logo.png
  app/src/main/res/drawable/shape_home_12_retc_rounded.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🍭 [DEVELOP], 🍎 [나경], 🏂 [점핏]

#22 develop: 검색 페이지 네트워크 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/now/jumpit/data/local/dao/RecentKeywordDao.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/request/gitkeep
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/SearchResult.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/SearchResultsResponse.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/service/NoticeService.kt
  app/src/main/java/com/sopt/now/jumpit/data/repository/SearchKeywordRepository.kt
  app/src/main/java/com/sopt/now/jumpit/ui/common/base/BaseFactory.kt
  app/src/main/java/com/sopt/now/jumpit/ui/common/base/BindingActivity.kt
  app/src/main/java/com/sopt/now/jumpit/ui/common/base/BindingFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/home/HomeFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/jumpit/JumpitActivity.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumeFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/search/SearchFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/search/SearchViewModel.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchCategoryDialog.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchResultAdapter.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchResultFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchResultViewModel.kt
  app/src/main/res/drawable/bg_black_radius_3.xml
  app/src/main/res/drawable/bg_white_radius_top_3.xml
  app/src/main/res/drawable/selector_search_category_background.xml
  app/src/main/res/drawable/selector_search_category_font.xml
  app/src/main/res/drawable/selector_search_category_stroke.xml
  app/src/main/res/layout/activity_jumpit.xml
  app/src/main/res/layout/dialog_search_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/menu/menu_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🍭 [DEVELOP], 🐸 [준서], 🏂 [점핏]

#25 develop: 홈프래그먼트 UI 수정
  app/src/main/res/layout/fragment_home.xml
Labels: 🍭 [DEVELOP], 🍂 [가을], 🏂 [점핏]

#26 develop: 기업 상세 페이지 UI 및 서버 통신 구현
  app/src/androidTest/java/com/sopt/now/jumpit/ExampleInstrumentedTest.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/DetailResponse.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/response/SimilarCompanyDummyData.kt
  app/src/main/java/com/sopt/now/jumpit/data/remote/service/NoticeService.kt
  app/src/main/java/com/sopt/now/jumpit/ui/detail/DetailFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/detail/DetailSimilarPositionAdapter.kt
  app/src/main/java/com/sopt/now/jumpit/ui/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/now/jumpit/ui/resume/ResumeFragment.kt
  app/src/main/java/com/sopt/now/jumpit/ui/searchResult/SearchResultFragment.kt
  app/src/main/res/drawable/detail_banner_pass.xml
  app/src/main/res/drawable/detail_btn_apply.xml
  app/src/main/res/drawable/detail_btn_banner_diff.xml
  app/src/main/res/drawable/detail_btn_bookmark.xml
  app/src/main/res/drawable/detail_btn_coach_robotics.xml
  app/src/main/res/drawable/detail_icn_back.xml
  app/src/main/res/drawable/detail_icn_notification.xml
  app/src/main/res/drawable/detail_icn_share.xml
  app/src/main/res/drawable/ic_detail_70money.xml
  app/src/main/res/drawable/ic_detail_arrow_r_black.xml
  app/src/main/res/drawable/ic_detail_bmk_normal.xml
  app/src/main/res/drawable/ic_detail_duplicate.xml
  app/src/main/res/drawable/ic_detail_heart.xml
  app/src/main/res/drawable/ic_detail_place.xml
  app/src/main/res/drawable/ic_detail_toggledown.xml
  app/src/main/res/drawable/img_detail_dummy.png
  app/src/main/res/drawable/item_detail_skill_backgroud.xml
  app/src/main/res/drawable/shape_blue_light1_fill_5_rect.xml
  app/src/main/res/drawable/shape_gray2_stroke_3_rect.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_similar_position.xml
  app/src/main/res/layout/item_skill.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  gradle/libs.versions.toml
Labels: 🍭 [DEVELOP], 🍎 [나경], 🏂 [점핏]

#23 develop: 과제 리드미 추가
  README.md
Labels: 🍭 [DEVELOP], 🐸 [준서], 🏂 [점핏]
